# Generated by Django 5.0.7 on 2024-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0002_delete_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=400, unique=True)),
                ("username", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
