# Generated by Django 5.0.7 on 2024-07-30 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
