# Generated by Django 5.0.7 on 2024-07-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
