# Generated by Django 5.0.7 on 2024-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_products_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="catogery",
            field=models.CharField(
                choices=[
                    ("mens", "mens"),
                    ("womens", "womens"),
                    ("kids", "kids"),
                    ("sports", "sports"),
                    ("reguler", "reguler"),
                ],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
