# Generated by Django 5.0.7 on 2024-08-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_usercart"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="usercart",
            name="total",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
