# Generated by Django 5.0.7 on 2024-08-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_order_email_order_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("canceled", "canceled"),
                ],
                default=1,
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
